create table public.levels (
  id bigint generated by default as identity not null,
  uuid uuid null default gen_random_uuid (),
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  deleted_at timestamp with time zone null,
  local_id integer null,
  is_synced boolean null default true,
  operation_type text null,
  constraint levels_pkey primary key (id),
  constraint levels_name_key unique (name),
  constraint levels_uuid_key unique (uuid)
) TABLESPACE pg_default;



create table public.offices (
  id bigint generated by default as identity not null,
  uuid uuid null default gen_random_uuid (),
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  deleted_at timestamp with time zone null,
  local_id integer null,
  is_synced boolean null default true,
  operation_type text null,
  constraint offices_pkey primary key (id),
  constraint offices_name_key unique (name),
  constraint offices_uuid_key unique (uuid)
) TABLESPACE pg_default;

create table public.students (
  id bigint generated by default as identity not null,
  uuid uuid null default gen_random_uuid (),
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  deleted_at timestamp with time zone null,
  local_id integer null,
  is_synced boolean null default true,
  operation_type text null,
  birth_date text null,
  phone text null,
  address text null,
  office_id integer not null default 1,
  level_id integer not null default 1,
  constraint students_pkey primary key (id),
  constraint students_name_key unique (name),
  constraint students_uuid_key unique (uuid),
  constraint fk_level foreign KEY (level_id) references levels (id) on delete set null,
  constraint fk_office foreign KEY (office_id) references offices (id) on delete set null
) TABLESPACE pg_default;